- set_fact:
    packages_type_dir: "{{ project_dir }}/packages/{{ package.type }}"

- set_fact:
    packages_type_group_dir: "{{ packages_type_dir }}/{{ package.dir }}"
    package_parent_dir: "{{ packages_type_dir }}/{{ package.dir }}"
    package_dir: "{{ packages_type_dir }}/{{ package.dir }}/{{ package.name }}"
    package_dir_name: "{{ package.dir }}/{{ package.name }}"
  when:
    package.dir is defined

- set_fact:
    package_dir: "{{ packages_type_dir }}/{{ package.name }}"
    package_parent_dir: "{{ packages_type_dir }}"
    package_dir_name: "{{ package.name }}"
  when:
    package.dir is undefined

- name: "Check if type directory for package {{ package.name }} exists"
  stat:
      path: "{{ packages_type_dir }}"
  register: packages_type_dir_status

- name: "Create {{ packages_type_dir }} directory"
  file:
       path: "{{ packages_type_dir }}"
       state: directory
  when:
    packages_type_dir_status.stat.exists == False

- name: "Check if group directory for package {{ package.name }} exists"
  stat:
      path: "{{ packages_type_group_dir }}"
  register: packages_type_group_dir_status

- name: "Create group directory for {{ package.name }}"
  file:
       path: "{{ packages_type_group_dir }}"
       state: directory
  when:
    packages_type_group_dir_status.stat.exists == False

- name: "Check if directory for package {{ package.name }} exists"
  stat:
      path: "{{ package_dir }}"
  register: package_dir_status

- name: "Create skeleton for package {{ package.name }}"
  vars:
    package_type: "python-and-template"
    nso_install_dir: "{{ nqde_dir }}/nso-bin/nso-{{ package.nso_version }}"
  shell: "source {{ nso_install_dir }}/ncsrc &&  ncs-make-package  --service-skeleton {{ package_type }} {{ package.name }}"
  args:
    chdir: "{{ package_parent_dir }}"
    executable: /bin/bash
  when:
    package_dir_status.stat.exists == False and (package.type == 'dev' or package.type =='standard')

- name: "Copy YANG modules for standard package{{ package.name }}"
  get_url:
    url: https://raw.githubusercontent.com/YangModels/yang/master/standard/{{ package.org }}/{{ item.branch }}/{{ item.name }}%40{{ item.version }}.yang
    dest: "{{ package_dir }}/{{ package.name }}/src/yang/{{ item.name }}.yang"
  loop:
      "{{ package.yang_modules }}"
  when:
    package.type == 'standard'

- name: "Delete default template for standard package {{ package.name }}"
  file:
    path: "{{ package_dir }}/{{ package.name }}/templates/{{ package.name }}-template.xml"
    state: absent
  when:
    package.type == 'standard'

- name: "Change makefile for standard package {{ package.name }}"
  lineinfile:
    path: "{{ package_dir }}/{{ package.name }}/src/Makefile"
    insertbefore: '^NCSCPATH.*'
    line: 'YANGPATH += yang/'
  when:
    package.type == 'standard'

- name: "Clone package {{ package.name }} from git"
  git:
    repo: "{{ package.git_clone.url }}"
    dest: "{{ package_dir }}/{{ package.name }}"
  when:
    package.type == 'git_clone'

- name: "Create symbolic link for shared package {{ package.name }}"
  file:
    src: "{{ shared_packages_localhost_dir }}/{{ package_dir_name }}"
    dest: "{{ package_dir }}"
    state: link
  when:
    package.type == 'shared'

  # TODO: compile must be done at runtime creation
#- name: "Compile package"
#  include_role:
#      name: dev/make_package
#  vars:
#      package_name: "{{ package.name }}"
#      package_parent_dir: "{{ package_parent_dir }}"

  # TODO: old remove

#- name: "Create symbolic link from run-time directory for package {{ package.name }}"
#  file:
#    src: "{{ package_dir }}/{{ package.name }}"
#    dest: "{{ project_run_dir }}/packages/{{ package.name }}"
#    state: link

#- name: "Check if package {{ package.name }} exists"
#  stat:
#      path: "{{ project_dir }}/dev/packages/{{ package.name }}"
#  register: package_dev_dir_status

#  when:
#     package_dev_dir_status.stat.exists == False

# https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-network-topology%402018-02-26.yang
# https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-network%402018-02-26.yang
-

