- name: "Check if package {{ package_name }} exists"
  stat:
      path: "{{ project_dir }}/dev/packages/{{ package_name }}"
  register: package_dev_dir_status

- name: Create package
  shell: "source {{ nso_install_dir }}/ncsrc &&  ncs-make-package  --service-skeleton python-and-template {{ package_name }}"
  args:
    chdir: "{{ project_dir }}/dev/packages"
    executable: /bin/bash
  when:
     package_dev_dir_status.stat.exists == False



