- name: Find archive files for all NEDs
  find:
      paths: "{{ neds_localhost_dir }}/"
      patterns: "ncs*.tar.gz"
  register: find_result

- name: Set ned_archive_list variable
  set_fact:
     ned_archive_list: "{{ find_result.files | map(attribute='path') | list }}"

- name: Set ned_format variable
  set_fact:
      ned_format: ".*%s-%s.*\\.tar\\.gz"

- debug:
    var: ned_archive_list

- debug:
    var: ned_list_only_other_full_name_notype_unique

- debug:
    msg: 'ned_format|format("cisco-iosxr-7.30")'

- debug:
    msg: '{{ ned_archive_list | map("regex_search",ned_format|format("cisco-iosxr", "7.39")) | select("string") | list | first }}'

- name: install non-netsim NEDs
  unarchive:
     src: '{{  ned_archive_list | map("regex_search",ned_format|format(item.name, item.version)) | select("string") | list | first }}'
     dest: "{{ project_run_dir }}/packages/"
  loop:
     "{{ ned_list_only_other_full_unique }}"
-
#- name: install non-netsim NEDs
#  unarchive:
#     src: '{{  ned_archive_list | map("regex_search",".*%s.*\\.tar\\.gz"|format(item.ned)) | select("string") | list | first }}'
#     dest: "{{ project_run_dir }}/packages/"
#  when:
#     ned_list_only_other | select('search',item.ned) | list | length >0
#  loop:
#     "{{ non_netsim_device_list }}"

# TODO: do recompiling only for NEDs that require it
- name: recompile non-netsim NEDs
  shell: "source {{ nso_install_dir }}/ncsrc && make clean && make"
  args:
    chdir: "{{ project_run_dir }}/packages/{{ item.name }}-{{ item.type }}-{{ item.version }}/src"
    executable: /bin/bash
  loop:
     "{{ ned_list_only_other_full_unique }}"
