- name: Sync shared packages
  include_role:
      name: sync_package
  vars:
      package_name: "{{ item }}"
      shared: "true"
  loop:
      "{{ shared_packages }}"
  when:
      shared_packages is defined

- name: Compile shared packages
  include_role:
      name: make_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ shared_packages }}"
  when:
      shared_packages is defined

- name: Sync local packages
  include_role:
      name: sync_package
  vars:
      package_name: "{{ item }}"
      shared: "false"
  loop:
      "{{ packages }}"
  when:
      packages is defined

- name: Compile local packages
  include_role:
      name: make_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ packages }}"
  when:
      packages is defined

#- name: Sync shared packages
#  synchronize:
#     src: "{{ playbook_dir }}/shared-packages/{{ item }}"
#     dest: "{{ project_run_dir }}/packages/{{ item }}"
#  loop:
#      "{{ shared_packages }}"
#  when:
#      shared_packages is defined

