- set_fact:
    ned_dir: "{{ neds_localhost_dir }}/{{ netsim_device.ned}}"

- name: "Check if NED directory {{ ned_dir }} exists"
  stat:
      path: "{{ ned_dir }}"
  register: ned_dir_status

- name: "NED directory does not exist - abort playbook"
  meta: end_play
  when:
    ned_dir_status.stat.exists == False

- name: "Creating NETSIM device {{ netsim_device.name }} NED {{ netsim_device.ned }}"
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-netsim {{ netsim_device_action }} {{ ned_dir }} {{ netsim_device.name }}"
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
