- name: "Check if NSO directory {{ nso_install_dir }} exists"
  stat:
      path: "{{ nso_install_dir }}"
  register: nso_dir_status

- name: "NSO directory does not exist - abort playbook"
  meta: end_play
  when:
    nso_dir_status.stat.exists == False
 
- name: "Check if project directory {{ project_dir }} exists"
  stat:
      path: "{{ project_dir }}"
  register: project_dir_status

- name: create project directory
  file:
       path: "{{ project_dir }}"
       state: directory
  when:
    project_dir_status.stat.exists == False

- name: create project/dev directory
  file:
       path: "{{ project_dir }}/dev"
       state: directory

- name: create project/dev/packages directory
  file:
       path: "{{ project_dir }}/dev/packages"
       state: directory

#- name: "Check if run directory {{ project_run_dir }} exists"
#  stat:
#      path: "{{ project_run_dir }}"
#  register: project_run_dir_status

#- name: Remove run Directory
#  file:
#    path: "{{ project_dir }}/run"
#    state: absent

- name: Create run Directory
  file:
    path: "{{ project_run_dir }}"
    state: directory
 # when:
 #   project_run_dir_status.stat.exists == False


