- block:
  - name: "Deployment not specified - abort playbook"
    debug:
      msg: "Deployment not specified, aborting playbook"
  - meta: end_play
  when:
    deployment is not defined

- name: Set nqde_dir variable (localhost)
  set_fact:
       nqde_dir: "{{ nqde_localhost_dir }}"
  when:
       deployment == 'localhost'

- name: Set nqde_dir variable (docker)
  set_fact:
       nqde_dir: "/nqde"
  when:
       deployment == 'docker'

- name: Set nso_install_dir variable
  set_fact:
       nso_install_dir: "{{ nqde_dir }}/nso-bin/nso-{{ nso_version }}"

- name: Set project_dir variable
  set_fact:
       project_dir: "{{ nqde_dir }}/projects/{{ project_name }}"

- name: Set project_run_dir variable
  set_fact:
       project_run_dir: "{{ project_dir }}/run-{{ nso_version }}"

- name: Set netsim_device_list variable
  set_fact:
    netsim_device_list: "{{ ( devices | selectattr('type', 'equalto', 'netsim') | list) }}"

- name: Set non_netsim_device_list variable
  set_fact:
    non_netsim_device_list: "{{ ( devices | selectattr('type', 'ne', 'netsim') | list) }}"

- name: Set ned_list_all variable
  set_fact:
     ned_list_all: "{{ devices | map(attribute='ned') | list | unique }}"

- name: Set ned_list_netsim variable
  set_fact:
     ned_list_netsim: "{{ devices | selectattr('type', 'equalto', 'netsim') | map(attribute='ned') | list | unique }}"

#- debug: var=ned_list_netsim

- name: Set ned_list_other variable
  set_fact:
     ned_list_other: "{{ devices | selectattr('type', 'ne', 'netsim') | map(attribute='ned') | list | unique }}"

#- debug: var=ned_list_other

- name: Set ned_list_only_other variable
  set_fact:
     ned_list_only_other: "{{ ned_list_other | difference(ned_list_netsim) }}"

- name: Set empty netsim_device_list_full_dir
  set_fact:
     netsim_device_list_full_dir: []

# creates list of "<name>-<type>-version" strings for all netsim NEDs
- name: Set netsim_device_list_full_dir variable
  vars:
    full_name_dir: "{{ ned_list | selectattr('name', 'equalto', item.ned) | first }}"
    full_name: "{{ '{}-{}-{}'.format(full_name_dir.name, full_name_dir.type, full_name_dir.version) }}"
  set_fact:
     netsim_device_list_full_dir: "{{ netsim_device_list_full_dir }} + [ { 'name' : '{{ item.name }}', 'ned' : '{{ full_name }}' } ] "
  when:
     ned_list_netsim | select('search',item.ned) | list | length >0
  loop:
     "{{ netsim_device_list }}"

# creates list of "<name>-<type>-version" strings for all non-netsim NEDs

- name: Init ned_list_only_other_full_name
  set_fact:
     ned_list_only_other_full_name: []

- name: Set ned_list_only_other_full_name variable
  vars:
    full_name_dir: "{{ ned_list | selectattr('name', 'equalto', item.ned) | first }}"
    full_name: "{{ '{}-{}-{}'.format(full_name_dir.name, full_name_dir.type, full_name_dir.version) }}"
  set_fact:
     ned_list_only_other_full_name: "{{ ned_list_only_other_full_name }} + [ '{{ full_name }}' ] "
  when:
     ned_list_only_other | select('search') | list | length >0
  loop:
     "{{ non_netsim_device_list }}"

- name: Set ned_list_only_other_full_name_unique variable
  set_fact:
    ned_list_only_other_full_name_unique: "{{ ned_list_only_other_full_name | unique }}"

- name: Init ned_list_only_other_full
  set_fact:
     ned_list_only_other_full: []

- name: Set ned_list_only_other_full variable
  vars:
    ned_dict: "{{ ned_list | selectattr('name', 'equalto', item.ned) | first }}"
  set_fact:
     ned_list_only_other_full: "{{ ned_list_only_other_full + [{'name': ned_dict.name, 'type': ned_dict.type, 'version': ned_dict.version }] }}"
  when:
     ned_list_only_other | select('search') | list | length >0
  loop:
     "{{ non_netsim_device_list }}"

- debug:
    var: ned_list_only_other_full

- name: Set ned_list_only_other_full_unique variable
  set_fact:
    ned_list_only_other_full_unique: "{{ ned_list_only_other_full | unique }}"

- debug:
    var: ned_list_only_other_full_unique

# creates list of "<name>-<version>" strings for all non-netsim NEDs

- name: Set empty ned_list_only_other_full_name_notype
  set_fact:
     ned_list_only_other_full_name_notype: []

- name: Set ned_list_only_other_full_name_notype variable
  vars:
    full_name_dir: "{{ ned_list | selectattr('name', 'equalto', item.ned) | first }}"
    full_name: "{{ '{}-{}'.format(full_name_dir.name, full_name_dir.version) }}"
  set_fact:
     ned_list_only_other_full_name_notype: "{{ ned_list_only_other_full_name_notype }} + [ '{{ full_name }}' ] "
  when:
     ned_list_only_other | select('search') | list | length >0
  loop:
     "{{ non_netsim_device_list }}"

- name: Set ned_list_only_other_full_name_notype_unique variable
  set_fact:
    ned_list_only_other_full_name_notype_unique: "{{ ned_list_only_other_full_name_notype | unique }}"

- debug: var=ned_list_only_other_full_name_notype

- debug: var=ned_list_only_other_full_name_notype_unique
