
- name: Find unpacked NSO installation files
  find:
    paths: "{{ nso_bin_localhost_dir }}"
    patterns: "*linux.x86_64.installer.bin"
  register: find_result

- name: Show unpacked NSO installation files
  debug: var=find_result.files

- name: Set fact nso_install_list
  set_fact:
    nso_install_list: "{{ find_result.files | map(attribute='path') | list | map('regex_replace','.*nso.bin.(.*).linux.x86_64.installer.bin','\\1') | list }}"

- name: Show NSO install list
  debug: var=nso_install_list

- name: "Unpack NSO installation"
  shell: "sh {{ item }}.linux.x86_64.installer.bin {{ item }} --local-install"
  args:
    chdir: "{{ nso_bin_localhost_dir }}"
    executable: /bin/bash
  loop:
    "{{ nso_install_list }}"

- name: "Remove NSO installation files"
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    "{{ find_result.files }}"


