- set_fact:
    package_dir: "{{ project_dir }}/packages/{{ package.type }}"

- name: "Create symbolic link from run-time directory for package {{ package.name }}"
  file:
    src: "{{ package_dir }}/{{ package.name }}"
    dest: "{{ project_run_dir }}/packages/{{ package.name }}"
    state: link
