- name: "Check if run directory {{ project_run_dir }} exists"
  stat:
      path: "{{ project_run_dir }}"
  register: project_run_dir_status

- name: Create run directory
  file:
    path: "{{ project_run_dir }}"
    state: directory
  when:
    project_run_dir_status.stat.exists == False

- name: Create run Directory
  file:
    path: "{{ project_run_dir }}"
    state: directory

- name: Setup run Directory (wo netsim)
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --dest ."
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
  when:
    netsim_device_list | length == 0

- name: Setup run Directory (w/ netsim)
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --netsim-dir ./netsim --dest ."
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
  when:
    netsim_device_list | length > 0

- name: Create symbolic links to packages
  include_role:
      name: install/create_package_symlink
  vars:
      package: "{{ package_item }}"
  loop:
      "{{ packages }}"
  loop_control:
    loop_var: package_item
  when:
      packages is defined
