- name: Setup run Directory (wo netsim)
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --dest ."
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
  when:
    netsim_device_list | length == 0

- name: Setup run Directory (w/ netsim)
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --netsim-dir ./netsim --dest ."
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
  when:
    netsim_device_list | length > 0
