- name: "Compile package {{ package.name }}"
  shell: "source {{ nso_install_dir }}/ncsrc && make clean && make"
  args:
    chdir: "{{ project_dir }}/packages/{{ package.type }}/{{ package.name }}/src"
    executable: /bin/bash

