- name: Compile packages
  include_role:
      name: dev/make_package
  vars:
      package: "{{ package_item }}"
  loop:
      "{{ packages }}"
  loop_control:
    loop_var: package_item
  when:
      packages is defined

- name: Reload packages
  include_role:
      name: nso/packages_reload
  vars:
      package_name: "{{ item }}"
