- name: Set nso_install_dir variable
  set_fact:
       nso_install_dir: "{{ playbook_dir }}/nso-bin/nso-{{ nso_version }}"

- name: Set project_dir variable
  set_fact:
       project_dir: "{{ playbook_dir }}/projects/{{ project_name }}"

- name: Set project_run_dir variable
  set_fact:
       project_run_dir: "{{ project_dir }}/run-{{ nso_version }}"

- set_fact:
    netsim_device_list: "{{ ( devices | selectattr('type', 'equalto', 'netsim') | list) }}"
 
- set_fact:
     ned_list_all: "{{ devices | map(attribute='ned') | list | unique }}"

- set_fact:
     ned_list_netsim: "{{ devices | selectattr('type', 'equalto', 'netsim') | map(attribute='ned') | list | unique }}"

#- debug: var=ned_list_netsim

- set_fact:
     ned_list_other: "{{ devices | selectattr('type', 'ne', 'netsim') | map(attribute='ned') | list | unique }}"

- set_fact:
     ned_list_only_other: "{{ ned_list_other | difference(ned_list_netsim) }}"

#- debug: var=ned_list_only_other

