- name: Sync-from for all configs
  include_role:
     name: nso/sync_from
  vars:
     device_name: "{{ item.name }}"
  loop:
    "{{ netsim_device_list }}"
  when:
    item.config_file is defined

- name: "Load native configs"
  include_role:
     name: nso/call_action
  vars:
     action_path: "/ncs:devices/device{'{{ item.name }}'}/load-native-config"
     action_args: 
        source: "file {{project_dir }}/input/{{ item.config_file }}"
        mode: replace
  loop:
    "{{ netsim_device_list }}"
  when:
    item.config_file is defined

