- name: Sync shared packages
  include_role:
      name: dev/OLD_sync_package
  vars:
      package_name: "{{ item }}"
      shared: "true"
  loop:
      "{{ shared_packages }}"
  when:
      shared_packages is defined

- name: Compile shared packages
  include_role:
      name: dev/make_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ shared_packages }}"
  when:
      shared_packages is defined

- name: Redeploy shared packages
  include_role:
      name: nso/redeploy_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ shared_packages }}"
  when:
      shared_packages is defined

- name: Sync local packages
  include_role:
      name: dev/OLD_sync_package
  vars:
      package_name: "{{ item }}"
      shared: "false"
  loop:
      "{{ packages }}"
  when:
      packages is defined

- name: Compile local packages
  include_role:
      name: dev/make_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ packages }}"
  when:
      packages is defined

- name: Redeploy local packages
  include_role:
      name: nso/redeploy_package
  vars:
      package_name: "{{ item }}"
  loop:
      "{{ packages }}"
  when:
      packages is defined


