- name: Starting Netsim"
  shell: "source {{ nso_install_dir }}/ncsrc && ncs-netsim start"
  args:
    chdir: "{{ project_run_dir }}"
    executable: /bin/bash
  when:
    netsim_device_list | length > 0

