# Base image
FROM ubuntu:latest

# Install bases packages and cleanup
RUN apt-get update;\ 
    apt-get install -y openssh-client default-jre-headless ant make python python3;\
    apt-get -y clean autoclean;\
    apt-get -y autoremove;\
    rm -rf /tmp/* /var/tmp/* /var/lib/{apt,dpkg,cache,log}/

# Create nqde directories
RUN mkdir /nqde; \
    mkdir /nqde/projects

# Copy run-nso.sh
COPY run-nso.sh /nqde/

    
