- name: Find unpacked neds
  find:
    paths: "{{ neds_dir }}"
    patterns: "*.signed.bin"
  register: find_result

- debug: var=find_result.files

- name: "Unpack NED"
  shell: "sh {{ item.path }}"
  args:
    chdir: "{{ neds_dir }}"
    executable: /bin/bash
  loop:
    "{{ find_result.files }}" 

- name: "Remove NED-specific installation files"
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    "{{ find_result.files }}"

# get list of tar.gz archive files

- set_fact:
    ned_archive_list: "{{ find_result.files | map(attribute='path') | list | map('regex_replace','(.*).signed.bin','\\1.tar.gz') | list }}"

#  - debug: var=ned_archive_list

- name: Unpack NED archive (for netsim)
  unarchive:
      src: "{{ item }}"
      dest: "{{ neds_dir }}/"
  loop:
      "{{ ned_archive_list }}"

# do this also for "{{ neds_dir }}/{{ ned_base_filename }}.tar.gz.signature"

- name: "Remove NED common installation files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
      - "{{ neds_dir }}/README.signature"
      - "{{ neds_dir }}/cisco_x509_verify_release.py"
      - "{{ neds_dir }}/tailf.cer"
