- name: Find archive files for all NEDs
  find:
      paths: "{{ playbook_dir }}/nso-neds/"
      patterns: "ncs*.tar.gz"
  register: find_result

#- debug: var=find_result.files

- set_fact:
     ned_archive_list: "{{ find_result.files | map(attribute='path') | list }}"

#- debug: var=ned_archive_list

- set_fact:
      ned_format: ".*%s\\.tar\\.gz"

#- debug: var=ned_list_only_other


#- name: Find NED archive names
#  unarchive:
#      src: '{{  ned_archive_list | map("regex_search",ned_format|format(item)) | select("string") | list | first }}'
#      dest: "{{ project_run_dir }}/packages/"
#  loop:
#      "{{ ned_list_only_other }}"

- name: "Create authgroup"
  include_role:
     name: nso/create_cdb_node
  vars:
     node_data:
       tailf-ncs:devices:
         authgroups:
           group:
            - name: "authgroup-{{ item.name }}"
              default-map:
                remote-name: "{{ item.username }}"
                remote-password: "{{ item.password }}"
  loop:
    "{{ non_netsim_device_list }}"
  when:
    non_netsim_device_list | length > 0

- name: "Create non_netsim device"
  include_role:
    name: nso/create_cdb_device
  vars:
    create_device_name: "{{ item.name }}"
    create_device_address: "{{ item.address }}"
    create_device_ned: "{{ item.ned }}"
    create_device_authgroup: "authgroup-{{ item.name }}"
  loop:
    "{{ non_netsim_device_list }}"
  when:
    non_netsim_device_list | length > 0
