- name: Call action "{{ action_path }} (with arguments)"
  nso_action:
      url: "http://localhost:{{ api_port }}/jsonrpc"
      username: admin
      password: admin
      path: "{{ action_path }}"
      input: { "input": "{{  action_args }}" }     
  register: action_result
  when:
      action_args != ''

- name: Call action "{{ action_path }} (w/o arguments)"
  nso_action:
      url: "http://localhost:{{ api_port }}/jsonrpc"
      username: admin
      password: admin
      path: "{{ action_path }}"
  register: action_result
  when:
      action_args == ''
