---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: common/prepare_global_environment
    - role: common/prepare_project_common_environment
    - role: common/prepare_project_runtime_environment
    - role: run/start_netsim
    - role: run/start_nso
      vars:
         ncs_args: "--with-package-reload"
    - role: nso/create_non_netsim_devices

#    TODO: until nso_action module get resolved
#    - role: nso/load_native_config
