---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: common/prepare_global_environment
    - role: common/prepare_project_common_environment
    - role: common/prepare_project_runtime_environment
    - role: install/create_netsim_network
    - role: install/setup_run_directory
    - role: install/install_non_netsim_neds
    - role: dev/recompile_all_packages

