---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: common/prepare_global_environment
    - role: common/prepare_environment
    - role: run/start_netsim
    - role: run/start_nso
      vars:
         ncs_args: "--with-package-reload"
