- name: Create run directory
  file:
    path: "{{ project_run_dir }}"
    state: directory
  when:
    netsim_device_list | length > 0

- name: "Create netsim device"
  include_role:
    name: install/create_netsim_device
  vars:
    netsim_device: "{{ netsim_device_list_full_dir[0] }}"
    netsim_device_action: "create-device"
  when:
    netsim_device_list | length > 0

- name: "Add netsim device"
  include_role:
    name: install/create_netsim_device
  vars:
    netsim_device: "{{ netsim_device_list_full_dir[1] }}"
    netsim_device_action: "add-device"
  when:
    netsim_device_list | length == 2

- name: "Add netsim devices"
  include_role:
    name: install/create_netsim_device
  vars:
    netsim_device: "{{ item }}"
    netsim_device_action: "add-device"
  loop:
    "{{ netsim_device_list_full_dir[1:] | list }}"
  when:
    netsim_device_list_full_dir | length > 2
