- name: Set project_dir variable
  set_fact:
       project_dir: "{{ nqde_localhost_dir }}/projects/{{ project_name }}"

- name: "Check if project directory {{ project_dir }} exists"
  stat:
      path: "{{ project_dir }}"
  register: project_dir_status

- name: create project directory
  file:
       path: "{{ project_dir }}"
       state: directory
  when:
    project_dir_status.stat.exists == False

- name: create project/packages directory
  file:
       path: "{{ project_dir }}/packages"
       state: directory

- name: create project/input directory
  file:
       path: "{{ project_dir }}/input"
       state: directory

- name: Create skeleton project config files
  template:
      src: "nqde_project_skeleton_{{ item }}.j2"
      dest: "{{ project_dir }}/ncrf_config_{{ item }}.yml"
  loop:
    - "common"
    - "runtime"
    - "devices"
    - "packages"

- name: "Create symbolic link for active_runtime config"
  file:
    src: "{{ project_dir }}/ncrf_config_runtime.yml"
    dest: "{{ project_dir }}/ncrf_config_active_runtime.yml"
    state: link

- name: Create script files for roles
  template:
      src: "run_role.j2"
      dest: "{{ project_dir }}/{{ script.role_name }}.sh"
  loop:
      "{{ scripts.roles }}"
  loop_control:
    loop_var: script

- name: Chmod script files for roles
  file:
    path: "{{ project_dir }}/{{ script.role_name }}.sh"
    mode: '0777'
  loop:
      "{{ scripts.roles }}"
  loop_control:
    loop_var: script

- name: Create script files for playbooks
  template:
      src: "run_playbook.j2"
      dest: "{{ project_dir }}/{{ script.playbook_name }}.sh"
  loop:
      "{{ scripts.playbooks }}"
  loop_control:
    loop_var: script

- name: Chmod script files for playbooks
  file:
    path: "{{ project_dir }}/{{ script.playbook_name }}.sh"
    mode: '0777'
  loop:
      "{{ scripts.playbooks }}"
  loop_control:
    loop_var: script