- name: Set project_dir variable
  set_fact:
       project_dir: "{{ nqde_localhost_dir }}/projects/{{ project_name }}"

- name: "Check if project directory {{ project_dir }} exists"
  stat:
      path: "{{ project_dir }}"
  register: project_dir_status

- name: create project directory
  file:
       path: "{{ project_dir }}"
       state: directory
  when:
    project_dir_status.stat.exists == False

- name: create project/packages directory
  file:
       path: "{{ project_dir }}/packages"
       state: directory

- name: create project/input directory
  file:
       path: "{{ project_dir }}/input"
       state: directory

- name: Create skeleton project file
  template:
      src: "nqde_project_skeleton.j2"
      dest: "{{ project_dir }}/{{ project_name }}.yml"

- name: Create script files
  template:
      src: "run_role.j2"
      dest: "{{ project_dir }}/{{ script.role_name }}.sh"
  loop:
      "{{ scripts }}"
  loop_control:
    loop_var: script

- name: Chmod script files
  file:
    path: "{{ project_dir }}/{{ script.role_name }}.sh"
    mode: '0777'
  loop:
      "{{ scripts }}"
  loop_control:
    loop_var: script

